### ISSUE TITLE
Permission Issues with Tickets

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#1]
### Background (please fill out the following information):
- Bot Build/Version: v1.0.0

### Describe the bug
There are a few discovered permissions issues that occurs with the auto-configured channel permissions for support tickets.

### To Reproduce
1. User creates a ticket.
2. `supportRole` lacks permission to send messages in the channel and close the ticket.

### Expected behavior
`supportRole` should be able to send messages in the ticket channel, they should also be able to close the ticket.

**Comment by bleachyblue** [comment]
Bug has been fixed in the latest commit
