### ISSUE TITLE
Additions to the notice in tickets

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#10]
### Is your feature request related to a problem?
There's always a possibility that the team has put on some sort of notice when users open new tickets. This notice is usually meant to inform the people about possible current slow response times and similar cases.

### Describe the solution you'd like
The embed containing the notice in the ticket should not be deleted along everything else, and while we're there it should also be pinned alongside everything else.

### Describe alternatives you've considered
There's a couple possible options that can be done instead of the mentioned above solution.
1. Delete the notice message **but** repost it _before_ the "Ticket Information" embed.
2. Add a command letting the support agents repost this embed, even though it's at the very top of the channel.

### Additional context
n/a

**Comment by bleachyblue** [comment]
repost message after ticket information embed, before ticket submitted

**Comment by bleachyblue** [comment]
Added in the latest commit.
