### ISSUE TITLE
Remove all "setup" messages on -announce

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#12]
### Is your feature request related to a problem?
When a user tries to announce using `-announce` they will be asked a plethora of questions via embeds by the bot, making the channel pretty clogged up for the moment.

### Describe the solution you'd like
After the announcement has been confirmed as correct and published, have Kloey remove all the messages used during the creation of the announcement. This would make the channel cleaner 

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by bleachyblue** [comment]
delete question & answer immediately after response

**Comment by bleachyblue** [comment]
Added in the latest commit
