### ISSUE TITLE
Only allow selected brand to view a ticket

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#13]
### Is your feature request related to a problem?
Yes.

### Describe the solution you'd like
The users part of the selected brand should be the only ones allowed to view the ticket. Currently, users with the support role and the brand role are allowed to view the ticket. Solely the users with the brand role and support "permissions" should view the ticket.

### Describe alternatives you've considered
No, but I could definitely see that this would need quite a bit of brainstorming to figure out good ways to handle this.

### Additional context
n/a

**Comment by bleachyblue** [comment]
Remove support role from channels when creating tickets and only include the brand they chose

**Comment by bleachyblue** [comment]
Added in the latest commit
