### ISSUE TITLE
-addcustomer & -editcustomer

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#14]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
**How to add a customer:**
1. Staff member runs `-addcustomer [mention/userid]`
2. Bot lists options and descriptions to the equivalent & asks the staff to select one option.
4. Staff member selects one of the options.
5. Bot asks for confirmation, staff member confirms or declines.
5.1. Confirm = bot gives roles, the process completed.
5.2. Decline = process cancelled. 

**How to modify a customer:**
1. Staff member runs `-editcustomer [mention/userid]`
2. Bot asks to pick one of the two options:
2.1. Delete = show the current customer level of the user and confirm the deletion.
2.2. Edit = lets you pick a customer level, excluding the current one applied. Confirmation required.
2.3. Cancel = cancels the process.

### Describe alternatives you've considered
Manually adding the role via Discord, using their built-in system.

### Additional context
n/a

**Comment by bleachyblue** [comment]
staff: -editcustomer @user edit
bot: this person already has customer
bot: would you like to remove this role
user: react tick/cross
bot: which role would you like to add?
user: mentions role
bot: confirm y/n?
