### ISSUE TITLE
UTF-8 JSON

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#15]
### Background (please fill out the following information):
- Bot Build/Version: v1.0.1

### Describe the bug
No emoji support in config files, the issue discovered by @bleachyblue will be reworked at some point.

### To Reproduce
1. Try and use an emoji in JSON
2. See the results

### Expected behavior
UTF-8 should be supported in the JSON config files.

**Comment by bleachyblue** [comment]
I have reconfigured the emojis in the config and removed the replace code in the formatter.
