### ISSUE TITLE
Watching "1 tickets"

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#4]
### Background (please fill out the following information):
- Bot Build/Version: v1.0.0

### Describe the bug
Shows "Watching 1 tickets" even though more then one ticket is active in the server.

![image](https://user-images.githubusercontent.com/56734956/102113172-00a7ff80-3e39-11eb-85cb-7685ee39ac41.png)

### To Reproduce
1. Wait for the game activity message to change.

### Expected behavior
Game activity should be: "Watching X tickets" — x = amount of open tickets.

**Comment by bleachyblue** [comment]
Fixed in the latest commit
