### ISSUE TITLE
Toggle the creation of tickets

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#6]
### Is your feature request related to a problem?
During, let's say, a holiday season, most of our team might not be available and ready to support. Therefore there should be a way for us in management to disable the creation of tickets, either via the config or by a command.

### Describe the solution you'd like
1. A admin runs the command
2. Bot asks for a custom message (with support for formatting)
3. Admin gives a custom message
4. Bot asks for confirmation, admin accepts
5. User creates a ticket, gets treated with an embed by the bot containing the custom message.

### Describe alternatives you've considered
This could either be done via a command, but possibly via the config file too—it doesn't really matter.

### Additional context
n/a

**Comment by bleachyblue** [comment]
Note: When the user tries to make a ticket, it will attempt to DM them if it can't post the embed in the ticket channel

**Comment by bleachyblue** [comment]
The feature has been added in the latest commit.
