### ISSUE TITLE
-help outputs an error

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#7]
### Background (please fill out the following information):
- Bot Build/Version: v1.0.1

### Describe the bug
When a user runs `-help` it outputs a 400 error.

### To Reproduce
1. Run `-help`
2. Wait for the "Something went wrong" embed

### Expected behavior
![img](https://user-images.githubusercontent.com/56734956/102868732-d8249480-443a-11eb-9e55-3b6942e95448.png)

**Comment by bleachyblue** [comment]
Forgot to blacklist the new cog that changes the bots status, having no commands caused it to error. This has been fixed in the latest commit.
