### ISSUE TITLE
Additional users to a ticket doesn't get send access

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#8]
### Background (please fill out the following information):
- Bot Build/Version: v1.0.1

### Describe the bug
When a user gets added to a ticket, they automatically receive the denial to send messages **instead** of the approval to send messages.

### To Reproduce
1. Create a ticket, walk through the setup.
2. Add someone else to the ticket using `-add`
3. Check the permissions on that ticket channel.

### Expected behavior
When the support team adds an additional user to the ticket, that new user should also be able to send messages in that ticket just like everybody else with access to it.

**Comment by bleachyblue** [comment]
This issue has been fixed in the latest commit.
