### ISSUE TITLE
Conditions for auto-close

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#9]
### Is your feature request related to a problem?
It’s likely that our team won’t be able to answer before auto-close kicks in. The customer shouldn’t have to take the negative effects of seeing the auto-close timer turning on just because the staff team hasn’t had time to respond yet.

### Describe the solution you'd like
The auto-close timer should only be triggered after staff has responded to the user in the ticket. If the most recent message is already from a user then auto-close shouldn’t be counting down until staff has responded.

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by bleachyblue** [comment]
I'll be able to get this done most likely in the next few days, just got a few things going on.

**Comment by bleachyblue** [comment]
The system has been re-worked and is currently being tested.
